### ISSUE TITLE
How to use one cookie for all How to use one cookie for all ?

### ISSUE THREAD

**Issue by wku** [theelous3/asks#11]
example:
In order to parse the site you need one set of cookies, for all requests with one connections, the first time you access the site, you get the necessary cookies within the session, and all the further requests go already with the necessary cookies - approx.
If we use several connections, then the first hits of all connections without cookies occur, how do we make use of one cookie for any number of connections ?

async def hsession_t_stateful(s):
    r = await s.get()

@curio_run
async def session_stateful():
    s = HSession(
        'http://0.0.0.0:8080', persist_cookies=True, connections=1)
    async with curio.TaskGroup() as g:
        for _ in range(100):
            await g.spawn(hsession_t_stateful(s))

How to do this for Session and Session
connections = 1 -> works
connections = 10 -> not working

**Comment by theelous3** [comment]
Hi. This is interesting!

When you spawn an asks task, its request object may be constructed long before your target server sends any kind of response. 

Say we allow ten connections and spawn ten `.get()`s from our session. All of the resquests are build and ready to go pretty much instantly, and go off to make the requests as soon as they can.

This means that if you spawn all of the tasks at the same time (like in your for loop) there is no way that any one task can be aware of any cookies that any of the other 9 tasks may get in the future.

If lots of your requests depend on getting an initial cookie, you can use a pattern like this, where you use one request to prime the cookies.

```py
import asks
import curio
from pprint import pprint

async def worker():
    r = await s.get()
    return r.json()


async def main():
    await s.get(path='/set', params={'test': 'value'}) # prime the cookies
    async with curio.TaskGroup() as g:
        for _ in range(10):
            await g.spawn(worker()) # all of these will persist cookies based on the first request
        async for task in g:
            pprint(task.result)

s = asks.HSession('http://httpbin.org',
                  endpoint='/cookies',
                  persist_cookies=True,
                  connections=10)

curio.run(main())
```

I'm going to look in to another way to do this, but due to the nature of the beast, I'm not sure there's a good way to deal with this (at least off the top of my head.)

**Comment by wku** [comment]
Yes, I understand, everything is logical, everything works) thanks

**Comment by theelous3** [comment]
Just the nature of async! :D
