### ISSUE TITLE
Using lru cache on method to hit api and get the response

### ISSUE THREAD

**Issue by alexanderluiscampino** [theelous3/asks#170]
Hi,

First of all, I really like this library.
I have more of a general question rather than a issue. I'm using this to process thousands of records at a time, by hitting an API with query parameters, something of the sort:
```python
async def grabber(index: int, query_parameters):
         r = await session.get(url_endpoint, params=query_parameters, retries=5)
         data = await handle_response(index, r.json())
         await update_local_cache(index, query_parameters, data)

        results[index] = data
```
Many of these query parameters are a repeat from a previous hit, so instead of using the  API i'd like to check a local cache. Thought of using the decorator `@alru_cache(maxsize=32)` from [here](https://github.com/aio-libs/async_lru) to make that true.

Got this beautifully crafted message instead:
```
TypeError: Trio got unexpected <generator object main.<locals>.grabber at 0x7f780e2b2900> – are you trying to use a library written for asyncio/twisted/tornado or similar? That won't work without some sort of compatibility shim.
```

Is there anything built-in in asks to use some sort of cache, that I am missing in the docs, or is this really not possible, without writing a whole cache lib to work with trio?

Best,
Alex

**Comment by theelous3** [comment]
This is a fun question, though I'm trying to get my head around it.

You have a `grabber` which is just grabbing whatever it's told with no particular control of its own. Your caller to this grabber is sometimes calling with repeat `params`?

So, a few things. Firstly, it's typical that params will be a dict, which isn't hashable, which memoisation doesn't like unless you freeze it.

Secondly, you're passing an index with each `grabber` call, which I presume is increasing or otherwise different for every call, and so you will have 0 cache hits because each set of args to `grabber` is unique (it doesn't matter that the `params` alone are repeated, the whole set of args must be different).

Thirdly, this seems like maybe the wrong place to control the reduction of IO in your particular case. If possible, I think you want to handle removing duplicate calls to begin with rather than hoping the cache will do it for you.

Anyway, I tried this with curio rather than trio, as curio is just less complex and easier to test these things with. Once I removed the index and passed some somewhat ok-but-hashable params, standard `lru_cache` worked no problem. If you want this to work with trio, after considering the above, I'd say just wrapping `lru_cache` in an `async def` decorator will be fine :)

**Comment by alexanderluiscampino** [comment]
@theelous3 ,

Thank you for the all the observation, definitively very pertinent. I learned the hard way that my grabber was badly structured, since I hit all difficulties you just mentioned! 

I ended up going the route of removing the duplicates before calling the API, that seemed to solve the problem pretty well.

But for future reference, would you mind expanding on the concept of wrapping the `lru_cache` in an `async def` decorator?

**Comment by theelous3** [comment]
> But for future reference, would you mind expanding on the concept of wrapping the lru_cache in an async def decorator?

Sorry for the delay :D

I just mean that in the future, if you are having trouble getting something to run because of complains of async, you can just put the call in to an async def to allow awaits within. Typically this will have no effect other than to allow your code to run.
