### ISSUE TITLE
Add trio support

### ISSUE THREAD

**Issue by merrellb** [theelous3/asks#18]
I know it is already on the radar but thought I would put it in as an issue.  It appears trio now has (unreleased) async file io :-)

**Comment by theelous3** [comment]
Yep. This is very much on my radar, though I appreciate the kick in the arse :)

Inbound!

**Comment by theelous3** [comment]
Hey, trio support is currently passing tests in the [trio_support](https://github.com/theelous3/asks/tree/trio_support) branch. Feel free to check it out whilst I take care of docs related busy work before merge :)

Would love to hear feedback.

Currently the api is changing, such that in order to select an event loop lib, you call asks' `.init()` function, like so:

```python
import trio
import asks
asks.init('trio')

# do whatever
```

The process is the same for both curio and trio, and you may switch libs by re-calling `.init()`! Magic!
