### ISSUE TITLE
asks.init() is ugly

### ISSUE THREAD

**Issue by yifeikong** [theelous3/asks#27]
why do we have to call `asks.init('curio')` at the beginning, it seems to be ugly.

**Comment by Zaab1t** [comment]
To support multiple frameworks (currently only `curio` and `trio`). There is no perfect solution for this problem, but the current api is explicit and avoids many problems that the other ideas we had had.

**Comment by theelous3** [comment]
It could be made "magic" but at the expense of potential bias between libs or weird catastrophic failure.

For example; if you have a virtualenv with both curio and trio installed, and want asks to figure out which library you're using you have two options.

1) asks defaults to one or the other (bad! bias for a library)
2) asks checks the already imported modules (further presuming you've only imported one) and selects that. Feesable, but what if you do:

```python
import asks
import curio

# do stuff
```

All of a sudden asks fails horribly because it's import was out of sync with requirements, and the most implicit api restraint of all time was violated. Also bad! You could take it a step further and have asks do its initialisation *after* its first use, but that is very backwards and contrary to the expected order of operations in a python lib.

The most explicit and even handed solution is to require asks be informed.

**Comment by yifeikong** [comment]
Thanks for your explanation, I did not think about the case when curio was imported after cuiro/trio.
