### ISSUE TITLE
Clarify in the documentation that sessions should be used whenever doing large numbers of requests

### ISSUE THREAD

**Issue by ric2b** [theelous3/asks#67]
As a new user of asks, I was running out of file descriptors/sockets because I didn't know I had to use sessions. More detail [here](https://github.com/python-trio/trio/issues/527#issuecomment-389468738), but I was basically under the impression that a simple `asks.post()` would close/clean a socket before finishing and the connection pooling offered by Sessions was mostly an optimization to avoid constantly creating/closing sockets.

The documentation does mention the use of sessions when making large numbers of requests but doesn't make it clear that it's pretty much a requirement to avoid running out of sockets, at least from my interpretation of these two pages:
https://asks.readthedocs.io/en/latest/index.html#a-bigger-little-example
https://asks.readthedocs.io/en/latest/a-look-at-sessions.html#

By the way, I loved how asks is pretty much a drop-in replacement for requests and how simple to use it is! :D

**Comment by theelous3** [comment]
Wait. This shouldn't happen. Will investigate.

**Comment by ric2b** [comment]
This is pretty much the code I was using, I just took out the url and post data and renamed the methods:
```python3
asks.init('trio')

async def send_message(limit):    
    async with limit:
        response = await asks.post(URL,  data=DATA)
    print(f'data: {DATA}, response status: {response.status_code}')

async def send_n_messages(n):
    limit = trio.CapacityLimiter(4)

    async with trio.open_nursery() as nursery:
        for i in range(n):
            nursery.start_soon(send_message, limit)       

trio.run(send_n_messages, 35000)
```

The messages pass through a Java Jetty server and end up in a RabbitMQ node, both running locally.

It's possible that the leak is on the Jetty server, it uses a small connection pool to talk to RabbitMQ but maybe keeps the client facing sockets open for longer than needed.

**Comment by theelous3** [comment]
Ok. I have a solution for this. I'll implement tonight :)

**Comment by ric2b** [comment]
Thanks! :)
So the difference between this approach and using a shared session will be just better performance with a shared session, right?

**Comment by theelous3** [comment]
Yep. I went in to a bit more detail on the trio issue, but I'll clarify here. (You've seen it there, but I may as well write it here for posterity.)

Behind the scenes, the base requests (`asks.get/post/etc`) all create a `Session` object, use it, and dump it. I was relying on python to GC the sockets, but it turns out we can create sockets much much faster than they are cleaned up, in most cases.

I'll be implementing some context-manager like behaviour on the `Session`, which I'll use in the base requests. May as well make that available for use generally too. I think it could be very nice :)

Example

```python
async def example(url_list):
    with asks.Session(connections=10) as s:
        for url in url_list:
            print(await s.get(url))
```

**Comment by njsmith** [comment]
Supporting context managers and `close` methods on both sessions and response objects seems like a good idea to me. You might also want to check whether you're creating any unnecessary reference loops inside these objects, since on CPython that delays garbage collection. But PyPy always delays garbage collection regardless of whether you have reference loops, so you still need explicit APIs for releasing resources.

**Comment by theelous3** [comment]
So, after a bit of investigation with context-managers and `.a/close` and `gc.collect` and so on, I cannot force the OS to clean the sockets.

Having checked, Requests also has this issue. It seems the only real solution is to use an `asks.Session` :)

If anyone has any ideas, I'm down to try them out, but until then I can't see a way to make this behave nicely. Making a big note of this in the docs seems like an excellent idea.

I'll add the context-manager stuff anyway just because it's nice.

**Comment by njsmith** [comment]
That seems weird to be... If you call a `close` method, then things should close! (Convincing the GC to automatically close things is a little more complicated.) Of course I'm not sure what you were trying or what might have gone wrong, but like... OSes do close sockets when asked :-)

**Comment by Zaab1t** [comment]
@njsmith there's a note on the stdlib socket.close method that says that you need to run `s.shutdown(); s.close()` to close them in a "timely fashion".

https://docs.python.org/3/library/socket.html#socket.socket.close

**Comment by theelous3** [comment]
Tried things like:

```python
    async def free_pool(self):
        while self:
            sock = self.pop()
            await sock.aclose()
            del sock
        gc.collect()
```
...and other such wangjanglings, where `free_pool` was called on `asks.Session.__aexit__` (the object there is a subclass of `deque`.)

The socket obj returned from trio's `open_tcp_stream` and its ssl friend, don't have shutdown. Gonna takey-looky-see.

**Comment by theelous3** [comment]
Note: I checked with stdlib sockets there, calling `.shutdown(socket.SHUT_RDWR)` and then `.close`ing, however the same thing happens.

I'm starting to wonder if the sockets we see in `TIME_WAIT` mode are even an issue.

**Comment by njsmith** [comment]
Ah-hah, yeah, there's a few things here I can help with. (This stuff is confusing!)

Conceptually, `shutdown` and `close` do different things: `shutdown` tells the kernel to change the TCP-level state of a socket (sending FIN packets and stuff like that), while `close` tells the kernel that your process doesn't need this socket handle anymore. But in most cases, this distinction is irrelevant, because when you `close` the last handle referring to a socket, then the OS will automatically perform a `shutdown(SHUT_RDWR)`. 

There are cases where you need finer grained control, but they're kind of obscure: for example, if you have a socket that's been `dup`ed, or that is shared between multiple processes, then the automatic shutdown won't happen until *all* the socket handles referring to that connection are `close`d. Or, sometimes you want to do fancy stuff like notify the other side that you aren't going to send any more data, but you still want to keep receiving data – you can do that with `shutdown(SHUT_WR)` (and trio's `SocketStream` exposes this as its `send_eof` method). 99.9% of the time though you can ignore `shutdown` entirely and just `close` sockets when you're done with them.

Regarding TIME_WAIT: yeah, these are fine, not an issue. The point of TIME_WAIT is to avoid some extremely rare edge cases in the TCP protocol, where you could open a connection, then close it, then open a second connection that happens to use the same magic values as the first connection, and then have delayed packets from the first connection accidentally get treated as if they were part of the second connection. I don't actually understand how this is even possible with modern TCP, which has countermeasures against evil bystanders forging fake packets; it seems like those should automatically handle accidentally forged packets as well. But I'm probably missing something.

Anyway, every TCP connection ends with one side or the other keeping some TIME_WAIT state for a while. Occasionally you need to be aware of this when running a busy server or when writing low-level socket code (example: the traditional bsd semantics for server sockets are kind of broken and there's a flag called `SO_REUSEADDR` you have to set to un-break them, except Windows is slightly different – but your library should take care of this kind of nonsense for you).

The two things about TIME_WAIT that are relevant here:

- for http, it's generally considered a bit better if the client side ends up with the TIME_WAIT rather than the server. It's not a big deal either way, but if asks is producing lots of TIME_WAIT sockets that's actually good!

- sockets in TIME_WAIT are something that the kernel keeps track of, without userspace having to be involved at all. After you `close` a socket, then it might hang around got a while in TIME_WAIT, but that's the kernel's problem, not yours. In particular, it's no longer using up any of your process's file descriptors, or otherwise being counted against you. As long as you `close` your sockets promptly, you won't hit the FD ulimit, so that's the thing asks should be worrying about.

**Comment by theelous3** [comment]
Alright, docs updated, socket closure enforced, and context manager behaviour added to ``Session``s :D

https://github.com/theelous3/asks/commit/04b2d037130a1a6dc5e19766025c2e1c8ad5cf5b

@njsmith great little write up, thanks! I went and found the relevant sections in the tcp rfc dealing with it. It's rare enough for an rfc to actually be enjoyable to read, and this was one of them :P
